export const SET_AUTH_USER = "SET_AUTH_USER";
export const SET_LOGIN_STEP = "SET_LOGIN_STEP";
export const SET_SESSION_DATA = "SET_SESSION_DATA";
export const SET_MAIN_MENU_STATE = "SET_MAIN_MENU_STATE";
export const SET_NAVBAR_MENU_STATE = "SET_NAVBAR_MENU_STATE";