export default {
  /** Session Action */
  SET_AUTH_USER: 'SET_AUTH_USER',
  SET_LOGIN_STEP: 'SET_LOGIN_STEP',
  SET_SESSION_DATA: 'SET_SESSION_DATA',
  SET_SESSISET_MAIN_MENU_STATEON_DATA: 'SET_SESSISET_MAIN_MENU_STATEON_DATA',
  SET_NAVBAR_MENU_STATE: 'SET_NAVBAR_MENU_STATE',
  SET_SESSION_EXPIRY_MODAL_STATE: 'SET_SESSION_EXPIRY_MODAL_STATE',
  SET_MAIN_MENU_STATE: 'SET_MAIN_MENU_STATE',
  SET_INSTANCES: 'SET_INSTANCES',
  SET_TEAMS: 'SET_TEAMS',
  SET_LOADING_VALUE: 'SET_LOADING_VALUE',
  RESET_SESSION_DATA: 'RESET_SESSION_DATA',
  SIGN_OUT: 'SIGN_OUT',

  // Setting dashboard page index
  SET_VIEW_INDEX: 'SET_VIEW_INDEX',

  // Incident Page
  GET_ACTION_TABS_REQUEST: 'GET_ACTION_TABS_REQUEST',
  GET_ACTION_TABS_SUCCESS: 'GET_ACTION_TABS_SUCCESS',
  GET_ACTION_TABS_FAIL: 'GET_ACTION_TABS_FAIL',

  // SET TAB INDEX
  SET_ACTION_TAB: 'SET_ACTION_TAB',

  // GET FIELD LIST
  GET_FIELD_LIST_REQUEST: 'GET_FIELD_LIST_REQUEST',
  GET_FIELD_LIST_SUCCESS: 'GET_FIELD_LIST_SUCCESS',
  GET_FIELD_LIST_FAIL: 'GET_FIELD_LIST_FAIL',

  // GET HEAD LIST
  GET_HEAD_LIST_REQUEST: 'GET_HEAD_LIST_REQUEST',
  GET_HEAD_LIST_SUCCESS: 'GET_HEAD_LIST_SUCCESS',
  GET_HEAD_LIST_FAIL: 'GET_HEAD_LIST_FAIL',

  // SAVE ACTION DATA
  SAVE_INCIDENT_DATA_REQUEST: 'SAVE_INCIDENT_DATA_REQUEST',
  SAVE_INCIDENT_DATA_SUCCESS: 'SAVE_INCIDENT_DATA_SUCCESS',
  SAVE_INCIDENT_DATA_FAIL: 'SAVE_INCIDENT_DATA_FAIL',
};
