export default {
    /**Session Action */
    SET_AUTH_USER: 'SET_AUTH_USER',
    SET_LOGIN_STEP: 'SET_LOGIN_STEP',
    SET_SESSION_DATA: 'SET_SESSION_DATA',
    SET_SESSISET_MAIN_MENU_STATEON_DATA: 'SET_SESSISET_MAIN_MENU_STATEON_DATA',
    SET_NAVBAR_MENU_STATE: 'SET_NAVBAR_MENU_STATE',
    SET_SESSION_EXPIRY_MODAL_STATE: 'SET_SESSION_EXPIRY_MODAL_STATE',
    SET_MAIN_MENU_STATE: 'SET_MAIN_MENU_STATE',
    SET_INSTANCES: 'SET_INSTANCES',
    SET_TEAMS: 'SET_TEAMS',
    SET_LOADING_VALUE: 'SET_LOADING_VALUE',
    RESET_SESSION_DATA: 'RESET_SESSION_DATA',
    SIGN_OUT: 'SIGN_OUT',

    // Setting dashboard page index
    SET_VIEW_INDEX: 'SET_VIEW_INDEX',
};
